name: PilotRevitIntegrator
env:
 ADMINISTATOR: "Ascon.Pilot.RevitShareListener.Administrator"
 ADMINISTATOR_RELEASE: "RevitShareListener.Administrator"
 REVIT_ADDIN: "PilotRevitAddin"
 REVIT_SHARE_LISTENER: "PilotRevitShareListener"
 REVIT_SHARE_LISTENER_CONSOLE:  "PilotRevitShareListener.Console"
 REVIT_SHARE_AGREGATOR: "Ascon.Pilot.SDK.RevitShareAgregator"
 SOLUTION: "Ascon.Pilot.SDK.RevitSample.sln"
 INSTALLER_FOLDER:  ${{ github.workspace }}\RSLInstaller
 INSTALLER_SOLUTION:  ${{ github.workspace }}\RSLInstaller\Installer.sln
 INSTALLERX64: ${{ github.workspace }}\RSLInstaller\Pilot-RvtShareListener_x64\bin\x64\Release\Pilot_RvtShareListener_x64.msi
 INSTALLERX86: ${{ github.workspace }}\RSLInstaller\Pilot-RvtShareListener_x86\bin\Release\Pilot_RvtShareListener_x86.msi
 RELESE_FOLDER: ${{ github.workspace }}\upload
  

on:
  push:
    branches: [ TestCi ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore packages
      run: |
           nuget restore ${{ env.SOLUTION }}
           nuget restore ${{ env.INSTALLER_SOLUTION }}
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build with MSBuild 
      run: msbuild ${{ env.SOLUTION }} -p:Configuration=Release
    - name: Build WIX
      run: msbuild ${{ env.INSTALLER_SOLUTION }} -p:Configuration=Release
    - name: tar
      run: |
          mkdir ${{ github.workspace }}\zip
          move ${{ github.workspace }}\${{ env.REVIT_SHARE_AGREGATOR }}\bin\Release\* ${{ github.workspace }}\zip
          cd ${{ github.workspace }}\zip
          tar -a -c -f ${{ env.REVIT_SHARE_AGREGATOR }}.zip *
    - name: Prepare files to release
      run: |
       mkdir ${{ env.RELESE_FOLDER }}
       move ${{ github.workspace }}\${{ env.ADMINISTATOR }}\bin\Release ${{ env.RELESE_FOLDER }}\${{ env.ADMINISTATOR_RELEASE }}
       move ${{ github.workspace }}\${{ env.REVIT_ADDIN }}\bin\Release ${{ env.RELESE_FOLDER }}\${{ env.REVIT_ADDIN }}
       move ${{ github.workspace }}\${{ env.REVIT_SHARE_LISTENER }}\bin\Release ${{ env.RELESE_FOLDER }}\${{ env.REVIT_SHARE_LISTENER }} 
       move ${{ github.workspace }}\${{ env.REVIT_SHARE_LISTENER_CONSOLE }}\bin\Release ${{ env.RELESE_FOLDER }}\${{ env.REVIT_SHARE_LISTENER_CONSOLE }}
       mkdir ${{ env.RELESE_FOLDER }}\${{ env.REVIT_SHARE_AGREGATOR }}
       move ${{ github.workspace }}\${{ env.REVIT_SHARE_AGREGATOR }}\bin\zip\Release\${{ env.REVIT_SHARE_AGREGATOR }}.zip ${{ env.RELESE_FOLDER }}\${{ env.REVIT_SHARE_AGREGATOR }}
       mkdir ${{ env.RELESE_FOLDER }}\Installer
       move ${{ env.INSTALLERX64 }} ${{ env.RELESE_FOLDER }}\Installer
       move ${{ env.INSTALLERX86 }} ${{ env.RELESE_FOLDER }}\Installer
      shell: cmd
    - name: tar
      run: |
          cd ${{ env.RELESE_FOLDER }}
          tar -a -c -f bins.zip *
    - uses: actions/upload-artifact@v2
      with:
       name: my-artifact
       path: |
        ${{ github.workspace }}\zip
