name: PilotRevitIntegrator
env:
 ADMINISTATOR: "Ascon.Pilot.RevitShareListener.Administrator"
 ADMINISTATOR_RELEASE: "RevitShareListener.Administrator"
 REVIT_ADDIN: "PilotRevitAddin"
 REVIT_SHARE_LISTENER: "PilotRevitShareListener"
 REVIT_SHARE_LISTENER_CONSOLE:  "PilotRevitShareListener.Console"
 REVIT_SHARE_AGREGATOR: "Ascon.Pilot.SDK.RevitShareAgregator"
 SOLUTION: "Ascon.Pilot.SDK.RevitSample.sln"
 INSTALLER_FOLDER:  ${{ github.workspace }}\RSLInstaller
 INSTALLER_SOLUTION:  ${{ github.workspace }}\RSLInstaller\Installer.sln
 INSTALLERX64: ${{ github.workspace }}\RSLInstaller\Pilot-RvtShareListener_x64\bin\x64\Release\Pilot_RvtShareListener_x64.msi
 INSTALLERX86: ${{ github.workspace }}\RSLInstaller\Pilot-RvtShareListener_x86\bin\Release\Pilot_RvtShareListener_x86.msi
 RELESE_FOLDER: ${{ github.workspace }}\upload
 

on:
  push:
    branches: [ TestCi ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore packages
      run: |
           nuget restore ${{ env.SOLUTION }}
           nuget restore ${{ env.INSTALLER_SOLUTION }}
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build with MSBuild 
      run: msbuild ${{ env.SOLUTION }} -p:Configuration=Release
    - name: Build WIX
      run: msbuild ${{ env.INSTALLER_SOLUTION }} -p:Configuration=Release
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%y.%m.%d')" 
    - name: tar
      run: |
          mkdir ${{ github.workspace }}\zip
          move ${{ github.workspace }}\${{ env.REVIT_SHARE_AGREGATOR }}\bin\Release\* ${{ github.workspace }}\zip
      shell: cmd
    - uses: papeloto/action-zip@v1
      with:
        files: zip/
        dest: ${{ env.REVIT_SHARE_AGREGATOR }}.zip
    - name: Prepare files to release
      run: |
       mkdir ${{ env.RELESE_FOLDER }}
       move ${{ github.workspace }}\${{ env.ADMINISTATOR }}\bin\Release ${{ env.RELESE_FOLDER }}\${{ env.ADMINISTATOR_RELEASE }}
       move ${{ github.workspace }}\${{ env.REVIT_ADDIN }}\bin\Release ${{ env.RELESE_FOLDER }}\${{ env.REVIT_ADDIN }}
       move ${{ github.workspace }}\${{ env.REVIT_SHARE_LISTENER }}\bin\Release ${{ env.RELESE_FOLDER }}\${{ env.REVIT_SHARE_LISTENER }} 
       move ${{ github.workspace }}\${{ env.REVIT_SHARE_LISTENER_CONSOLE }}\bin\Release ${{ env.RELESE_FOLDER }}\${{ env.REVIT_SHARE_LISTENER_CONSOLE }}
       mkdir ${{ env.RELESE_FOLDER }}\${{ env.REVIT_SHARE_AGREGATOR }}
       move ${{ env.REVIT_SHARE_AGREGATOR }}.zip ${{ env.RELESE_FOLDER }}\${{ env.REVIT_SHARE_AGREGATOR }}
       mkdir ${{ env.RELESE_FOLDER }}\Installer
       move ${{ env.INSTALLERX64 }} ${{ env.RELESE_FOLDER }}\Installer
       move ${{ env.INSTALLERX86 }} ${{ env.RELESE_FOLDER }}\Installer
      shell: cmd
    - name: tar
      run: |
          cd ${{ env.RELESE_FOLDER }}
          tar -a -c -f bins.zip *
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ env.RELESE_FOLDER }}\bins.zip
        asset_name: binaries${{ env.TAG_NAME }}
        tag: ${{ env.TAG_NAME }}
        overwrite: true
        body: "new release"
        file_glob: true
      env:
          TAG_NAME: ${{ steps.date.outputs.date }}.${{ github.run_id }}
