name: PilotRevitIntegrator
env:
 ADMINISTATOR: "Ascon.Pilot.RevitShareListener.Administrator"
 REVIT_ADDIN: "PilotRevitAddin"
 REVIT_SHARE_LISTENER: "PilotRevitShareListener"
 REVIT_SHARE_LISTENER_CONSOLE:  "PilotRevitShareListener.Console"
 REVIT_SHARE_AGREGATOR: "Ascon.Pilot.SDK.RevitShareAgregator"
 SOLUTION: "Ascon.Pilot.SDK.RevitSample.sln"
 INSTALLER_FOLDER:  ${{ github.workspace }}\RSLInstaller
 INSTALLER_SOLUTION:  ${{ github.workspace }}\RSLInstaller\Installer.sln
 RELESE_FOLDER: ${{ github.workspace }}\upload

on:
  push:
    branches: [ TestCi ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore packages
      run: |
           nuget restore ${{ env.SOLUTION }}
           nuget restore ${{ env.INSTALLER_SOLUTION }}
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build with MSBuild 
      run: msbuild ${{ env.SOLUTION }} -p:Configuration=Release
    - name: Build WIX
      run: msbuild ${{ env.INSTALLER_SOLUTION }} -p:Configuration=Release
    - name: Prepare files to release\
      run: |
       mkdir ${{ env.RELESE_FOLDER }}
       move ${{ github.workspace }}\${{ env.REVIT_ADDIN }}\bin\Release ${{ env.RELESE_FOLDER }}\${{ env.REVIT_ADDIN }}
       move ${{ github.workspace }}\${{ env.REVIT_SHARE_LISTENER }}\bin\Release ${{ env.RELESE_FOLDER }}\${{ env.REVIT_SHARE_LISTENER }} 
       move ${{ github.workspace }}\${{ env.REVIT_SHARE_LISTENER_CONSOLE }}\bin\Release ${{ env.RELESE_FOLDER }}\${{ env.REVIT_SHARE_LISTENER_CONSOLE }}
       move ${{ github.workspace }}\${{ env.ADMINISTATOR }}\bin\Release ${{ env.RELEASE_FOLDER }}\${{ env.ADMINISTATOR_RELEASE }}
       move ${{ github.workspace }}\${{ env.REVIT_SHARE_AGREGATOR }}\bin\Release ${{ env.RELEASE_FOLDER }}\${{ env.REVIT_SHARE_AGREGATOR }}
    - uses: actions/upload-artifact@v2
      with:
       name: my-artifact
       path: |
        ${{ env.RELESE_FOLDER }}
