name: PilotRevitIntegrator
env:
 ADMINISTATOR: "Ascon.Pilot.RevitShareListener.Administrator"
 ADMINISTATOR_RELEASE: "RevitShareListener.Administrator"
 REVIT_ADDIN: "PilotRevitAddin"
 REVIT_SHARE_LISTENER: "PilotRevitShareListener"
 REVIT_SHARE_LISTENER_CONSOLE:  "PilotRevitShareListener.Console"
 REVIT_SHARE_AGREGATOR: "Ascon.Pilot.SDK.RevitShareAgregator"
 SOLUTION: "Ascon.Pilot.SDK.RevitSample.sln"
 INSTALLER_FOLDER:  ${{ github.workspace }}\RSLInstaller
 INSTALLER_SOLUTION:  ${{ github.workspace }}\RSLInstaller\Installer.sln
 INSTALLERX64: ${{ github.workspace }}\RSLInstaller\Pilot-RvtShareListener_x64\bin\x64\Release\Pilot_RvtShareListener_x64.msi
 INSTALLERX86: ${{ github.workspace }}\RSLInstaller\Pilot-RvtShareListener_x86\bin\Release\Pilot_RvtShareListener_x86.msi
 RELESE_FOLDER: ${{ github.workspace }}\upload
 

on:
  push:
    branches: [ TestCi ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
       dotnet-version: 3.1.301 
    - name: Nuget restor
      run: |
           nuget restore ${{ env.SOLUTION }}
           nuget restore ${{ env.INSTALLER_SOLUTION }}
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Build wix' obj
      run:  ${{ env.INSTALLER_FOLDER }}\packages\WiX.3.11.1\tools\candle.exe -dSolutionDir=${{ env.INSTALLER_FOLDER }} -dSolutionExt=.sln -dSolutionFileName=Installer.sln -dSolutionName=Installer -dSolutionPath=${{ env.INSTALLER_FOLDER }}\Installer.sln -dConfiguration=Release -dOutDir=${{ env.INSTALLER_FOLDER }}\Pilot-RvtShareListener_x64\obj\x64\Release\ -dPlatform=x64 -dProjectDir=${{ env.INSTALLER_FOLDER }}\Pilot-RvtShareListener_x64\ -dProjectExt=.wixproj -dProjectFileName=Pilot-RvtShareListener_x64.wixproj -dProjectName=Pilot-RvtShareListener_x64 -dProjectPath=${{ env.INSTALLER_FOLDER }}\Pilot-RvtShareListener_x64\Pilot-RvtShareListener_x64.wixproj -dTargetDir=${{ env.INSTALLER_FOLDER }}\Pilot-RvtShareListener_x64\bin\x64\Release\ -dTargetExt=.msi -dTargetFileName=Pilot_RvtShareListener_x64.msi -dTargetName=Pilot_RvtShareListener_x64 -dTargetPath=${{ env.INSTALLER_FOLDER }}\Pilot-RvtShareListener_x64\bin\x64\Release\Pilot_RvtShareListener_x64.msi -out ${{ env.INSTALLER_FOLDER }}\Pilot-RvtShareListener_x64\obj\x64\Release\ -arch x64 -ext ..\packages\WiX.3.11.1\tools\WixUtilExtension.dll -ext ..\packages\WiX.3.11.1\tools\WixUIExtension.dll "${{ env.INSTALLER_FOLDER }}\Pilot-RvtShareListener_x64\Components.wxs" "${{ env.INSTALLER_FOLDER }}\Pilot-RvtShareListener_x64\Product.wxs">${{ github.workspace }}\output.txt
